news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='news'),
    path('add-blog/', views.addBlog, name='add-blog')
]

timates/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name="home"),
    path('findpartner/', include('findpartner.urls')),
    path('news/', include('news.urls')),
    path('tournament/', include('championship.urls')),
    path('venue/', include('venue.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

venue/urls.py
'''
URLs for Venue
'''
from django.urls import path
from .views import index, venue_page

urlpatterns = [
    path('', index, name="venue_list"),
    path('<int:id>', venue_page, name="venue_page"),
]

venue/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone

# Create your models here.
class Venue(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='venue_img/')
    address = models.CharField(max_length=75)
    short_address = models.CharField(max_length=20)
    open_hour = models.TimeField(default='07:00:00')
    close_hour = models.TimeField(default='22:00:00')
    price = models.IntegerField()

    #Venue Type
    category = models.CharField(max_length=20)
    # field_type = models.TextField(max_length=20)
    # ground_type = models.TextField(max_length=20)


    #Facilities
    shower = models.BooleanField(default=False)
    locker = models.BooleanField(default=False)
    parking_space = models.BooleanField(default=False)
    food = models.BooleanField(default=False)
    wifi = models.BooleanField(default=False)
    shop = models.BooleanField(default=False)

    def __str__(self):
        return self.name

venue/forms.py
from django import forms
from .models import Venue

class VenueBookForm(forms.Form):
    datetime = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    venue = forms.ModelChoiceField(queryset=Venue.objects.all().order_by('name'))

    def __init__(self, *args, **kwargs):
        super(VenueBookForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control bg-primary'
            visible.field.widget.attrs['autocomplete'] = 'off'

venue/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Venue
from .forms import VenueBookForm

# Create your views here.
def index(request):
    form = VenueBookForm(request.POST or None)
    if request.method == "POST" and form.is_valid:
            pass #todo -> integrasi booking dengan findpartner / turnamen
    response = {
        'venues': Venue.objects.all() if Venue.objects.all() else None,
        'venue_book_form' : form
    }
    return render(request, 'venue_list.html', response)

def venue_page(request, id):
    response = {
        'venue' : get_object_or_404(Venue, id=id),
    }
    return render(request, 'venue_page.html', response)

venue/templates/venue_base.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock title %}
{% block head %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <!-- Timates Venue CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock head %}
{% block content %}
{% endblock content %}

venue/templates/venue_booking_form.html
{% load static %}
<style>
    .venue-form-body{
        padding-top: 10%;
        height: 70vh;
        background: url(/static/img/form-bg.jpg) no-repeat center;
    }
</style>
<div class="venue-form-body text-white">
    <div class="d-flex justify-content-around">
        <h1>Book Now!</h1>
    </div>
    <div class="d-flex justify-content-around">
        <form method="POST" class="w-25">
            {% csrf_token %} 
            {{ venue_book_form }}
            <div class="text-center">
                <input type="submit" class="m-4 btn btn-success text-white">
            </div>
        </form>
    </div>
</div>
<script>
    $(function () {
        $("#id_datetime").datetimepicker({
        format: 'd/m/Y H:i',
        });
    });
</script>

venue/templates/venue_booking_page.html
{% extends 'venue_base.html' %}
{% load static %}
{% block title %}Book Venue{% endblock title %}
{% block content %}
{% include 'venue_booking_form.html' %}
{% endblock content %}

venue/templates/venue_list.html
{% extends 'venue_base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Timates - Venue{% endblock title %}
{% block content %}
{% include 'venue_booking_form.html' %}
<style>
    a:hover{
        text-decoration: none;
    }
    .card-deck {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        grid-gap: .5rem;
    }
    .card{
        transition: 0.3s;
    }
    .card:hover{
        transform: scale(1.05);
    }
</style>
<h2 class="text-body text-center text-info mt-4">Official Venue Partners</h2>
<div class="venue-list d-flex justify-content-center flex-wrap m-5">
    {% if venues %}
    <div class="card-deck">   
        {% for venue in venues %}
            <div class="card venue-card">
                <a href="{% url 'venue_page' venue.id %}">
                    <img class="card-img-top venue-img" src="{{ venue.image.url }}" alt="Venue Image">
                    <div class="card-body">
                        <h3 class="card-title venue-name text-info">{{ venue.name|title }}</h3>
                        <p class="card-text text-muted venue-location">{{ venue.short_address|title }}</p>
                        <p class="card-text text-muted venue-price">Mulai dari <span class="text-danger">Rp. {{ venue.price|intcomma }}</span></p>
                        <p class="card-text text-muted venue-category">{{ venue.category|title }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-light" role="alert">There's currently no venues in our database<br>Please contact our admin.</div>
    {% endif %}
</div>
{% endblock content %}

venue/templates/venue_page.html
{% extends 'venue_base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{ venue.name|title }}{% endblock title %}
{% block content %}
<style>
    .unavailable{
        filter:grayscale(1);
    }
    .card{
        width:100%;
        height:auto;
    }
    .card-img {
        filter: sepia(100%) hue-rotate(190deg) saturate(100%) brightness(0.4);
    }
</style>
<div class="d-flex justify-content-center m-5">
    <div class="card bg-dark text-white w-75 mt-5">
        <img src="{{ venue.image.url }}" class="card-img venue-page-img" alt="Venue Image">
        <div class="card-img-overlay">
            <h3 class="card-title venue-page-name">{{ venue.name|title }}</h5>
                <p class="card-text description">Operational Hour</p>
                <h4 class="card-text venue-page-address">{{ venue.open_hour }} - {{ venue.close_hour }}</h4>
                <p class="card-text description">Address</p>
                <h4 class="card-text venue-page-address">{{ venue.address|title }}</h4>
                <p class="card-text description">Price</p>
            <h4 class="card-text venue-page-price text-danger">Rp. {{ venue.price|intcomma }}</h4>
            <p class="card-text description ">Category</p>
            <h4 class="card-text venue-page-category">{{ venue.category }}</h4>
            <a href="{% url 'venue_list' %}" class="btn btn-primary text-center my-2">Book Now!</a>
        </div>
    </div>
    <div class="facilities mt-5">
        <div class="facility m-3 justify-content-around {{ venue.shower|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/shower.svg' %}">
                    <p>Shower</p>
                </div>
            </label>
        </div>
        <div class="facility m-3 justify-content-around {{ venue.locker|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/locker.svg' %}">
                    <p>Locker</p>
                </div>
            </label>
        </div>
        <div class="facility m-3 justify-content-around {{ venue.parking_space|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/parking_space.svg' %}">
                    <p>Parking Space</p>
                </div>
            </label>
        </div>
        <div class="facility m-3 justify-content-around {{ venue.food|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/food.svg' %}">
                    <p>Food</p>
                </div>
            </label>
        </div>
        <div class="facility m-3 justify-content-around {{ venue.wifi|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/wifi.svg' %}">
                    <p>Wifi</p>
                </div>
            </label>
        </div>
        <div class="facility m-3 justify-content-around {{ venue.shop|yesno:',unavailable' }}">
            <label>
                <div>
                    <img src="{% static 'img/shop.svg' %}">
                    <p>Shop</p>
                </div>
            </label>
        </div>
    </div>
</div>
{% endblock content %}